import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';
import 'db.dart';
import 'marathi.dart';

const markets=['श्रीदेवी','टाइम','मिलन डे','कल्याण','श्रीदेवी नाईट','मिलन नाईट','मेन','बाजार'];

void main() async { WidgetsFlutterBinding.ensureInitialized(); await DB.init(); runApp(const App()); }
class App extends StatelessWidget { const App({super.key}); @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'एजंटचा हिशोब',locale:const Locale('mr','IN'),theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.teal),home:const Home()); }

class Home extends StatefulWidget { const Home({super.key}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home> {
  final agent=TextEditingController(); final search=TextEditingController(); final shot=ScreenshotController(); final agentFocus=FocusNode(); Timer? _typingTimer;
  final d=List<String>.filled(8,''); final g=List<String>.filled(8,'');
  final cellControllersD=List.generate(8,(_)=>TextEditingController()); final cellControllersG=List.generate(8,(_)=>TextEditingController());
  final date=DateTime.now(); double old=0; String oldSide=''; List<String> agents=[]; bool sending=false;
  double v(String s)=>double.tryParse(s)??0; double get td=>d.fold(0,(a,b)=>a+v(b)); double get tg=>g.fold(0,(a,b)=>a+v(b)); double get diff=>(td-tg).abs();
  String get side=>td>tg?'देणे':tg>td?'घेणे':''; double get signedOld=>oldSide=='देणे'?old:oldSide=='घेणे'?-old:0; double get finalSigned=>signedOld+td-tg; double get finalAmount=>finalSigned.abs(); String get finalSide=>finalSigned>0?'देणे':finalSigned<0?'घेणे':'';
  String money(double x)=>x==x.roundToDouble()?x.toInt().toString():x.toStringAsFixed(2); String oldText()=>old==0?'-':'₹${money(old)} $oldSide'; String finalText()=>finalAmount==0?'-':'₹${money(finalAmount)} $finalSide';
  @override void initState(){super.initState();loadAgents();}
  @override void dispose(){_typingTimer?.cancel();agentFocus.dispose();agent.dispose();search.dispose();for(final x in cellControllersD)x.dispose();for(final x in cellControllersG)x.dispose();super.dispose();}
  Future<void> loadAgents()async{agents=await DB.agents();if(mounted)setState((){});}
  Future<void> load()async{final a=agent.text.trim();if(a.isEmpty)return;final ds=DateFormat('yyyy-MM-dd').format(date);final p=await DB.previous(a,ds);final r=await DB.day(a,ds);setState((){old=p.amount;oldSide=p.side;for(int i=0;i<8;i++){d[i]=r?['d${i+1}']?.toString()??'':'';g[i]=r?['g${i+1}']?.toString()??'':'';cellControllersD[i].text=d[i];cellControllersG[i].text=g[i];}});}
  Future<void> save()async{final a=agent.text.trim();if(a.isEmpty){_msg('कृपया एजंटचे नाव निवडा');return;}await DB.save(agent:a,date:DateFormat('yyyy-MM-dd').format(date),d:d,g:g,opening:old,openingSide:oldSide,closing:finalAmount,closingSide:finalSide);await loadAgents();_msg('हिशोब जतन झाला');}
  void _msg(String x)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));
  String report(){final b=StringBuffer();b.writeln('एजंटचा हिशोब\n');b.writeln('एजंट: ${agent.text.trim()}');b.writeln('दिनांक: ${DateFormat('dd-MM-yyyy').format(date)}\n');b.writeln('┌──────────────────┬──────────┬──────────┐');b.writeln('│ बाजार            │ देणे     │ घेणे     │');b.writeln('├──────────────────┼──────────┼──────────┤');for(int i=0;i<8;i++){final a=d[i].isEmpty?'-':money(v(d[i]));final z=g[i].isEmpty?'-':money(v(g[i]));b.writeln('│ ${markets[i].padRight(16)} │ ${a.padLeft(8)} │ ${z.padLeft(8)} │');}b.writeln('├──────────────────┼──────────┼──────────┤');b.writeln('│ एकूण             │ ${money(td).padLeft(8)} │ ${money(tg).padLeft(8)} │');b.writeln('└──────────────────┴──────────┴──────────┘');b.writeln();b.writeln('                              ${side.isEmpty?'-':money(diff)}');b.writeln('-----------------------------------');b.writeln(side.isEmpty?'      -                   -':'      $side                ${money(diff)}');b.writeln();b.writeln('मागची बाकी:        ${oldText()}');b.writeln('एकूण                   ${finalText()}');return b.toString();}

  Widget cell(int i,bool isD){final c=isD?cellControllersD[i]:cellControllersG[i];final own=isD?d[i]:g[i];final other=isD?g[i]:d[i];return TextField(controller:c,enabled:own.isNotEmpty||other.isEmpty,textAlign:TextAlign.center,keyboardType:const TextInputType.numberWithOptions(decimal:true),inputFormatters:[FilteringTextInputFormatter.allow(RegExp(r'[0-9.]'))],decoration:const InputDecoration(hintText:'-',contentPadding:EdgeInsets.symmetric(vertical:8)),onChanged:(x){setState((){if(isD){d[i]=x;if(x.isNotEmpty){g[i]='';cellControllersG[i].clear();}}else{g[i]=x;if(x.isNotEmpty){d[i]='';cellControllersD[i].clear();}}});});}

  Widget reportCard()=>Material(color:Colors.white,child:Container(width:700,padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('एजंटचा हिशोब',textAlign:TextAlign.center,style:TextStyle(fontSize:30,fontWeight:FontWeight.bold,color:Colors.teal.shade800)),const SizedBox(height:10),Text('एजंट: ${agent.text.trim()}'),Text('दिनांक: ${DateFormat('dd-MM-yyyy').format(date)}'),const SizedBox(height:14),Table(border:TableBorder.all(color:Colors.grey),children:[TableRow(children:['बाजार','देणे','घेणे'].map((x)=>Padding(padding:const EdgeInsets.all(8),child:Text(x,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold)))).toList()),...List.generate(8,(i)=>TableRow(children:[markets[i],d[i].isEmpty?'-':money(v(d[i])),g[i].isEmpty?'-':money(v(g[i]))].map((x)=>Padding(padding:const EdgeInsets.all(7),child:Text(x,textAlign:TextAlign.center))).toList())),TableRow(children:['एकूण',money(td),money(tg)].map((x)=>Padding(padding:const EdgeInsets.all(8),child:Text(x,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold)))).toList())]),const SizedBox(height:16),Text(side.isEmpty?'-':'${money(diff)}\n$side',textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:20)),const Divider(),Text('मागची बाकी: ${oldText()}'),Text('एकूण: ${finalText()}',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:20))])));

  Future<void> sharePhoto()async{final a=agent.text.trim();if(a.isEmpty){_msg('कृपया एजंट निवडा');return;}await save();setState(()=>sending=true);try{final Uint8List bytes=await shot.captureFromWidget(reportCard(),pixelRatio:3.0);final dir=await getTemporaryDirectory();final file=File('${dir.path}/hisab_${DateFormat('ddMMyyyy').format(date)}.png');await file.writeAsBytes(bytes);await Share.shareXFiles([XFile(file.path)],text:'$a चा हिशोब');}catch(e){_msg('फोटो तयार करताना अडचण आली');}if(mounted)setState(()=>sending=false);}

  @override Widget build(BuildContext c){final q=search.text.toLowerCase();final filtered=agents.where((x)=>x.toLowerCase().contains(q)||toMarathi(x).contains(search.text)).toList();return Scaffold(appBar:AppBar(title:const Text('एजंटचा हिशोब'),actions:[IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>History(agent.text.trim()))),icon:const Icon(Icons.history),tooltip:'इतिहास')]),body:ListView(padding:const EdgeInsets.all(12),children:[
    Text('दिनांक: ${DateFormat('dd-MM-yyyy').format(date)}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:10),
    TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),labelText:'एजंट शोधा',hintText:'एजंटचे नाव टाइप करा',border:OutlineInputBorder()),onSubmitted:(x){if(x.trim().isNotEmpty){agent.text=toMarathi(x.trim());search.clear();load();setState((){});}}),
    if(search.text.isNotEmpty&&filtered.isNotEmpty)Card(child:Column(children:filtered.take(10).map((a)=>ListTile(title:Text(toMarathi(a)),onTap:(){agent.text=toMarathi(a);search.clear();load();setState((){});})).toList())),
    const SizedBox(height:10),TextField(focusNode:agentFocus,controller:agent,decoration:const InputDecoration(labelText:'एजंटचे नाव',hintText:'इंग्रजीत लिहा, थोडा वेळ थांबा — मराठीत दिसेल',border:OutlineInputBorder()),onChanged:(x){_typingTimer?.cancel();if(x.trim().isEmpty)return;_typingTimer=Timer(const Duration(milliseconds:550),(){final m=toMarathi(agent.text.trim());if(m!=agent.text){agent.value=TextEditingValue(text:m,selection:TextSelection.collapsed(offset:m.length));}load();});},onSubmitted:(x){final m=toMarathi(x.trim());agent.value=TextEditingValue(text:m,selection:TextSelection.collapsed(offset:m.length));load();}),const SizedBox(height:12),
    Card(child:Padding(padding:const EdgeInsets.all(5),child:Column(children:[Container(padding:const EdgeInsets.symmetric(vertical:11),color:Theme.of(c).colorScheme.surfaceContainerHighest,child:const Row(children:[Expanded(flex:2,child:Text('बाजार',textAlign:TextAlign.center,style:TextStyle(fontWeight:FontWeight.bold))),Expanded(child:Text('देणे',textAlign:TextAlign.center,style:TextStyle(fontWeight:FontWeight.bold))),Expanded(child:Text('घेणे',textAlign:TextAlign.center,style:TextStyle(fontWeight:FontWeight.bold)))])),...List.generate(8,(i)=>Padding(padding:const EdgeInsets.symmetric(vertical:2),child:Row(children:[Expanded(flex:2,child:Text(markets[i],textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w600))),Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:3),child:cell(i,true))),Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:3),child:cell(i,false)))]))),const Divider(),Row(children:[const Expanded(flex:2,child:Text('एकूण',textAlign:TextAlign.center,style:TextStyle(fontWeight:FontWeight.bold))),Expanded(child:Text(money(td),textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold))),Expanded(child:Text(money(tg),textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold)))])]))),
    Align(alignment:Alignment.centerRight,child:Text(side.isEmpty?'-':money(diff),style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18))),const Divider(),Row(children:[Expanded(child:Text(side.isEmpty?'-':side,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold))),Expanded(child:Text(side.isEmpty?'-':money(diff),textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold)))]),const SizedBox(height:12),Text('मागची बाकी:        ${oldText()}',style:const TextStyle(fontSize:16,fontWeight:FontWeight.w600)),const SizedBox(height:4),Text('एकूण                   ${finalText()}',style:const TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:18),SizedBox(height:50,child:FilledButton.icon(onPressed:save,icon:const Icon(Icons.save),label:const Text('हिशोब जतन करा'))),const SizedBox(height:8),SizedBox(height:50,child:OutlinedButton.icon(onPressed:sending?null:sharePhoto,icon:const Icon(Icons.photo),label:Text(sending?'फोटो तयार होत आहे...':'व्हॉट्सॲपवर फोटो पाठवा')))
  ]);}
}

class History extends StatefulWidget {final String agent;const History(this.agent,{super.key});@override State<History> createState()=>_HistoryState();}
String _marathiDate(String iso){final d=DateTime.tryParse(iso);return d==null?iso:DateFormat('dd-MM-yyyy').format(d);}

class _HistoryState extends State<History>{List<Map<String,dynamic>> rows=[];@override void initState(){super.initState();load();}Future<void> load()async{rows=await DB.history(widget.agent);if(mounted)setState((){});} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text('${widget.agent} — इतिहास')),body:rows.isEmpty?const Center(child:Text('जतन केलेला हिशोब नाही')):ListView.builder(itemCount:rows.length,itemBuilder:(_,i){final r=rows[i];return ListTile(title:Text(_marathiDate(r['date'].toString())),subtitle:Text('एकूण: ₹${r['closing']} ${r['closingSide']}'));}));}
